services:
    redis-server:
        image: 'redis'
        command: ["redis-server", "--protected-mode", "no"]
    node-app:
        build: ./
        image: docker.io/avikashmar28/visits
        ports:
            - "8081:8081"